In [1]:
import numpy
numpy.__version__

'1.15.1'

In [2]:
import numpy as np

In [3]:
import array
L = list(range(10))
A = array.array('i', L)
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [5]:
# np.array will convert all element within array to be the same type
np.array([3.14,44,2,4,])

array([ 3.14, 44.  ,  2.  ,  4.  ])

In [6]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Create Arrays from Scratch

In [7]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Create a 3x5 floating-point array filled with ones
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# Create a 3x3 array of uniformly distributed 
# random values between 0 and 1
np.random.random((3,3))

array([[0.08432136, 0.43296845, 0.69877065],
       [0.62187752, 0.77435174, 0.54502592],
       [0.52994047, 0.91755653, 0.00136971]])

In [13]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3,3))

array([[7, 1, 1],
       [3, 2, 8],
       [3, 1, 9]])

In [14]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist 
#    at that memory location
np.empty(3)

array([1., 1., 1.])

In [16]:
import numpy as np
np.random.seed(666)

# One-dimensional array
x1 = np.random.randint(10, size = 6)
# Two-dimensional array
x2 = np.random.randint(10, size=(3, 4))  
# Three-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))

In [17]:
print(x3)
print("Dimension = ", x3.ndim) # dimensions

print("Dimension = ", x3.shape) # shape
print("Dimension = ", x3.size) # number of records

[[[0 4 0 4 5]
  [7 1 0 0 6]
  [6 0 3 2 9]
  [2 6 0 6 0]]

 [[9 3 6 9 3]
  [2 4 8 7 7]
  [6 4 3 8 5]
  [3 3 5 9 9]]

 [[5 4 5 2 5]
  [4 4 9 0 4]
  [1 7 4 4 1]
  [7 5 2 2 2]]]
Dimension =  3
Dimension =  (3, 4, 5)
Dimension =  60


In [18]:
x1

array([2, 6, 9, 4, 3, 1])

In [19]:
print(x1[4])
print(x1[0])

3
2
